version: 0.1

phases:
  install:
    commands:
      - echo Install started on `date`
      - npm install
  pre_build:
    commands:
      - echo PreBuild started on `date`
      - cat build/production.json > config/production.json
      - sed -i -e 's/{DB_HOST}/${DB_HOST}/' config/production.json
  build:
    commands:
      - echo Build started on `date`
      - npm test
  post_build:
    commands:
      - aws cloudformation package --template-file samTemplate.yaml
                                   --s3-bucket mtg-omega-lambda
                                   --output-template-file newSamTemplate.yaml
artifacts:
  type: zip
  files:
    - newSamTemplate.yaml
