AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Imports articles from various feeds

Resources:
  MtgOmegaBatchFeedImport:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MtgOmega-Batch-FeedImport
      Description: Import specified feeds' articles into our database
      Timeout: 30
      Handler: dist/index.handler
      Runtime: nodejs4.3
      CodeUri: ./
      Role: arn:aws:iam::390360040979:role/lambda-batch
      VpcConfig:
        SecurityGroupIds:
          - sg-4a08f833
        SubnetIds:
          - subnet-1ee0ff68
          - subnet-b96932e1
          - subnet-4fb0af2b
      Environment:
        Variables:
          NODE_ENV: production
      Events:
        ImportFeed:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
