AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Imports articles from various feeds

Resources:
  MtgOmegaBatchFeedImport:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/debug.handler
      Runtime: nodejs4.3
      CodeUri: ./
      Role: arn:aws:iam::390360040979:role/lambda-batch
      VpcConfig:
        SecurityGroupIds:
          - sg-4a08f833
        SubnetIds:
          - subnet-db2693ad
          - subnet-be995ee6
          - subnet-310d8a55
      Environment:
        Variables:
          NODE_ENV: production
      Events:
        ImportFeed:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
