AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Imports articles from various feeds

Resources:
  MtgOmegaBatchFeedImport:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/debug.handler
      Runtime: nodejs4.3
      CodeUri: ./
      Environment:
        Variables:
          NODE_ENV: production
      Events:
        ImportFeed:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
